version: '3.9'

services:
  api:
    build: notification_event_api
    restart: always
    container_name: api
    ports:
      - "8000:8000"
    command: bash -c 'gunicorn main:app --workers 4
      --worker-class uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8000 --reload'
    env_file:
      - notification_event_api/src/core/.env.dev
#    logging:
#      driver: "json-file"
#      options:
#        max-file: "10"
#        max-size: "10m"
    depends_on:
      - mongo
      - rabbitmq3
#    healthcheck:
#      test: nc -z kafka-1 9092 || nc -z kafka-2 9092 || exit -1
#      start_period: 15s
#      interval: 5s
#      timeout: 10s
#      retries: 10

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./tmp/logs/nginx/:/var/log/nginx/:ro
    ports:
      - "80:80"
    depends_on:
      - api

  mongo:
    image: 'mongo:5.0.3'
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  rabbitmq3:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq3"
    restart: always
    env_file:
      - rabbitmq/.env
    volumes:
      - ./rabbitmq/data:/data
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3