version: '3.9'

services:
  api:
    build: notification_event_api
    restart: always
    container_name: api
    expose:
      - "8000"
    command: bash -c 'gunicorn main:app --workers 4
      --worker-class uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8000 --reload'
    env_file:
      - notification_event_api/src/core/.env.dev
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    depends_on:
      - mongo
      - rabbitmq3
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet && rabbitmq-diagnostics -q ping
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  enricher:
    build: enricher
    restart: always
    container_name: enricher
    expose:
      - "8006"
    command: bash -c 'gunicorn main:app --workers 4
      --worker-class uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8000 --reload'
    env_file:
      - enricher/src/core/.env
    depends_on:
      - api
      - mongo

  data_generator:
    build: fake_data_generator
    restart: always
    container_name: data_generator
    expose:
      - "8004"
    command: bash -c 'gunicorn main:app --workers 4
      --worker-class uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8000 --reload'
    env_file:
      - fake_data_generator/src/core/.env
    depends_on:
      - api

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    expose:
      - "80"
    depends_on:
      - api

  mongo:
    image: 'mongo:5.0.3'
    container_name: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  rabbitmq3:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq3"
    restart: always
    env_file:
      - rabbitmq/.env
    volumes:
      - ./rabbitmq/data:/data
    expose:
      # AMQP protocol port
      - "5672"
      # HTTP management UI
      - "15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  worker_low_priority:
    container_name: worker_low_priority
    build: worker
    env_file:
      - worker/src/core/.env.dev
    depends_on:
      - api
      - rabbitmq3
    command: bash -c 'python3 main.py'

  worker_high_priority:
    container_name: worker_low_priority
    build: worker
    env_file:
      - worker/src/core/.env.dev
    depends_on:
      - api
      - rabbitmq3
    command: bash -c 'python3 main.py --priority'
